### ISSUE TITLE
FRAPT doesn't export font 2 correctly

### ISSUE THREAD

**Issue by htruong** [viler-int10h/fontraption#1]
Reproduce:

- Switch to font 2.
- Edit the "A" character.
- Export to a .com file
- Run the com file.

Expected:

- Font 2 is changed, normal font doesn't change.

What I saw:

- "A" is replaced in font 1 of the VGA mem.

**Comment by viler-int10h** [comment]
What you're seeing is actually the expected behavior: the two font tabs are purely an editing feature (for easy copy/pasting, comparison etc.).  Whether you save/export from font tab 1 or 2 shouldn't affect the behavior of the result.

By design, the .com exports are intended to modify the default font (when they're run, and/or when a BIOS text mode is set).  I think it wouldn't really make sense to target a specific font block - there are very few programs out there that use two fonts simultaneously, and AFAIK they all supply their own fonts anyway, so they'd override any changes that a "generic" INT 10h-hooking TSR can make.  

For those cases, you'd need some code which is more specific to what the particular program is doing... I suspect it'd be easier to just find and patch the program's font data. :)

**Comment by htruong** [comment]
I wonder if you can kindly consider adding a switch to the exported COM program to potentially enable writing its font to slot 2 of the VGA memory,as a feature, then?

I'm writing a program to make use of 512 characters on DOS and thus wish to have such functionality for frapt. If so, I don't have to code up myself a program that does exactly what you're aready doing and good at. 

I also see that when font slot 2 and slot 1 are different then the VGA card is supposed to disregard bit 3 (brightness) of the text attribute but many emulators don't so the alternative font appear brighter than the main one. I know there is a workaround that needs to be done to [set the font 2 palette to be the same](https://www.oocities.org/siliconvalley/2926/tpsrc/mirror2pas.txt). I wonder if you could add the workaround also when changing font 2.

**Comment by viler-int10h** [comment]
Exporting .com to target different font banks would probably be too much for a "user-facing feature" - the problem is, VGA actually has 8 font slots (the entire A000 segment in Plane 2 can be used), and any two out of these 8 fonts can be active on screen simultaneously.  So trying to determine or adjust the exact setup would open up all kinds of configuration hell... and as mentioned, the particular setup is very application-specific.

Fontraption for example uses 5 of these slots in the editor, and swaps the 2 active ones as needed (generally there's one UI font and one user font).  There's a description of this setup at the beginning of [VGA.INC](https://github.com/viler-int10h/Fontraption/blob/master/VGA.inc).  The actual code for this should be in the routines ``vga_init_font_IO``, ``vga_upload_font``, and ``vga_end_font_IO``, so feel free to take it and adapt it to your needs- for a specific program, that's probably far easier and more direct than relying on an external .com anyway :)  I'd be happy to help with questions.

BTW, I'm not 100% sure that the VGA is expected to disregard attribute bit 3 as a palette bit in that situation... that workaround sounds like what I implemented in the editor (all palettes have 8 colors, repeated twice), but it *might* also be needed on the real hardware.  That is, I'm not sure the VGA will stop you if you really want two different color sets for your 2 fonts - I don't know though because I haven't actually tried doing that.

**Comment by htruong** [comment]
Thanks for the detailed answer! I appreciate it. Yeah I'm extremely new to DOS programming (and assembly) so it will take some time for this to soak in. I will ask you more as I understand more of this stuff.

> BTW, I'm not 100% sure that the VGA is expected to disregard attribute bit 3 as a palette bit in that situation...

I am [quoting wikipedia here so please forgive me](https://en.wikipedia.org/wiki/VGA_text_mode#:~:text=Two%20active,color%20palette.), but this seems pretty interesting:

> Two active font pointers (font A and font B) select two of the available fonts, although they usually point to the same font. When they each point to different fonts, attribute bit 3 (see above) acts as a font selection bit instead of as a foreground color bit. On real VGA hardware, this overrides the bit's use for color selection, but on many clones and emulators, the color selection remains — meaning one font is displayed as normal intensity, and the other as high-intensity. This error can be overcome by changing the palette registers to contain two copies of an 8-color palette.

I haven't been able to trace the origin of the claim but it *sounds credible* enough to investigate. Hope that's not some fake news...
